// exerciseImages.js — auto-generated by scripts/generate-exercise-images.mjs
// Illustration source: @bryllim/workout-guide v1.0.0 (302 exercises, 906 SVG frames)
// Assets: CC BY-SA 4.0 © Bryl Lim (https://bryllim.com) — derived from Everkinetic.
// Code: MIT. Attribution must be preserved when shipping these images.

export const IMAGE_BASE = 'https://bryllim.github.io/workout-guide/frames';

/**
 * Returns { url, alt, secondaryMuscles, isStretch } or null.
 * frame is 1-based; defaults to frame 1 (start position).
 */
export function getExerciseImage(exerciseId, frame = 1){
  const entry = EXERCISE_IMAGES[exerciseId];
  if(!entry) return null;
  const n = Math.max(1, Math.min(entry.frames.length, Math.round(frame)));
  return {
    url: `${IMAGE_BASE}/${entry.slug}/frame-${n}.svg`,
    alt: entry.primaryMuscle + ' exercise',
    primaryMuscle: entry.primaryMuscle,
    secondaryMuscles: entry.secondaryMuscles,
    isStretch: entry.isStretch,
    license: entry.license,
    creator: entry.creator,
  };
}

/** Returns true if this exercise has illustration frames available. */
export function hasExerciseImage(exerciseId){
  return !!EXERCISE_IMAGES[exerciseId];
}

/** Returns available frame indices for an exercise. */
export function getImageFrames(exerciseId){
  const entry = EXERCISE_IMAGES[exerciseId];
  return entry ? entry.frames : [];
}

/** Returns all package slugs not yet mapped to an Arise exercise (for library expansion). */
export function getUnmatchedSlugs(){
  return [
  {
    "slug": "incline-bench-press",
    "name": "Incline Bench Press",
    "muscle": "Chest",
    "equipment": "Barbell"
  },
  {
    "slug": "dumbbell-bench-press",
    "name": "Dumbbell Bench Press",
    "muscle": "Chest",
    "equipment": "Dumbbell"
  },
  {
    "slug": "decline-bench-press",
    "name": "Decline Bench Press",
    "muscle": "Chest",
    "equipment": "Barbell"
  },
  {
    "slug": "machine-chest-press",
    "name": "Machine Chest Press",
    "muscle": "Chest",
    "equipment": "Machine"
  },
  {
    "slug": "pec-deck",
    "name": "Pec Deck",
    "muscle": "Chest",
    "equipment": "Machine"
  },
  {
    "slug": "weighted-push-up",
    "name": "Weighted Push-up",
    "muscle": "Chest",
    "equipment": "Bodyweight"
  },
  {
    "slug": "seated-dumbbell-press",
    "name": "Dumbbell Seated Shoulder Press",
    "muscle": "Shoulders",
    "equipment": "Dumbbell"
  },
  {
    "slug": "cable-lateral-raise",
    "name": "Cable Lateral Raise",
    "muscle": "Shoulders",
    "equipment": "Cable"
  },
  {
    "slug": "front-raise",
    "name": "Front Raise",
    "muscle": "Shoulders",
    "equipment": "Dumbbell"
  },
  {
    "slug": "upright-row",
    "name": "Upright Row",
    "muscle": "Shoulders",
    "equipment": "Barbell"
  },
  {
    "slug": "deadlift",
    "name": "Deadlift",
    "muscle": "Posterior Chain",
    "equipment": "Barbell"
  },
  {
    "slug": "t-bar-row",
    "name": "T-Bar Row",
    "muscle": "Back",
    "equipment": "Machine"
  },
  {
    "slug": "dumbbell-bent-over-row",
    "name": "Dumbbell Bent Over Row",
    "muscle": "Back",
    "equipment": "Dumbbell"
  },
  {
    "slug": "machine-row",
    "name": "Machine Row",
    "muscle": "Back",
    "equipment": "Machine"
  },
  {
    "slug": "close-grip-lat-pulldown",
    "name": "Close-Grip Lat Pulldown",
    "muscle": "Lats",
    "equipment": "Cable"
  },
  {
    "slug": "assisted-pull-up",
    "name": "Assisted Pull-up",
    "muscle": "Lats",
    "equipment": "Machine"
  },
  {
    "slug": "weighted-pull-up",
    "name": "Weighted Pull-up",
    "muscle": "Lats",
    "equipment": "Bodyweight"
  },
  {
    "slug": "shrug",
    "name": "Barbell Shrug",
    "muscle": "Upper Back",
    "equipment": "Barbell"
  },
  {
    "slug": "squat",
    "name": "Squat",
    "muscle": "Quads",
    "equipment": "Barbell"
  },
  {
    "slug": "hack-squat",
    "name": "Hack Squat",
    "muscle": "Quads",
    "equipment": "Machine"
  },
  {
    "slug": "walking-lunge",
    "name": "Walking Lunge",
    "muscle": "Quads",
    "equipment": "Dumbbell"
  },
  {
    "slug": "leg-extension",
    "name": "Leg Extension",
    "muscle": "Quads",
    "equipment": "Machine"
  },
  {
    "slug": "leg-curl",
    "name": "Leg Curl",
    "muscle": "Hamstrings",
    "equipment": "Machine"
  },
  {
    "slug": "seated-leg-curl",
    "name": "Seated Leg Curl",
    "muscle": "Hamstrings",
    "equipment": "Machine"
  },
  {
    "slug": "standing-calf-raise",
    "name": "Standing Calf Raise",
    "muscle": "Calves",
    "equipment": "Machine"
  },
  {
    "slug": "seated-calf-raise",
    "name": "Seated Calf Raise",
    "muscle": "Calves",
    "equipment": "Machine"
  },
  {
    "slug": "preacher-curl",
    "name": "Preacher Curl",
    "muscle": "Biceps",
    "equipment": "Machine"
  },
  {
    "slug": "cable-curl",
    "name": "Cable Curl",
    "muscle": "Biceps",
    "equipment": "Cable"
  },
  {
    "slug": "reverse-curl",
    "name": "Reverse Curl",
    "muscle": "Forearms",
    "equipment": "Barbell"
  },
  {
    "slug": "wrist-curl",
    "name": "Wrist Curl",
    "muscle": "Forearms",
    "equipment": "Barbell"
  },
  {
    "slug": "skull-crusher",
    "name": "Skull Crusher",
    "muscle": "Triceps",
    "equipment": "Barbell"
  },
  {
    "slug": "close-grip-bench-press",
    "name": "Close-Grip Bench Press",
    "muscle": "Triceps",
    "equipment": "Barbell"
  },
  {
    "slug": "assisted-dip",
    "name": "Assisted Dip",
    "muscle": "Triceps",
    "equipment": "Machine"
  },
  {
    "slug": "hanging-leg-raise",
    "name": "Hanging Leg Raise",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "cable-crunch",
    "name": "Cable Crunch",
    "muscle": "Core",
    "equipment": "Cable"
  },
  {
    "slug": "ab-wheel",
    "name": "Ab Wheel Rollout",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "running",
    "name": "Running",
    "muscle": "Legs",
    "equipment": "Cardio"
  },
  {
    "slug": "walking",
    "name": "Walking",
    "muscle": "Legs",
    "equipment": "Cardio"
  },
  {
    "slug": "cycling",
    "name": "Cycling",
    "muscle": "Legs",
    "equipment": "Cardio"
  },
  {
    "slug": "rowing",
    "name": "Rowing",
    "muscle": "Back",
    "equipment": "Cardio"
  },
  {
    "slug": "stair-climber",
    "name": "Stair Climber",
    "muscle": "Legs",
    "equipment": "Cardio"
  },
  {
    "slug": "incline-cable-fly",
    "name": "Incline Cable Fly",
    "muscle": "Chest",
    "equipment": "Cable"
  },
  {
    "slug": "decline-dumbbell-press",
    "name": "Decline Dumbbell Press",
    "muscle": "Chest",
    "equipment": "Dumbbell"
  },
  {
    "slug": "smith-machine-bench-press",
    "name": "Smith Machine Bench Press",
    "muscle": "Chest",
    "equipment": "Machine"
  },
  {
    "slug": "landmine-press",
    "name": "Landmine Press",
    "muscle": "Shoulders",
    "equipment": "Barbell"
  },
  {
    "slug": "chest-dip",
    "name": "Chest Dip",
    "muscle": "Chest",
    "equipment": "Bodyweight"
  },
  {
    "slug": "weighted-dip",
    "name": "Weighted Dip",
    "muscle": "Triceps",
    "equipment": "Bodyweight"
  },
  {
    "slug": "standing-dumbbell-press",
    "name": "Standing Dumbbell Press",
    "muscle": "Shoulders",
    "equipment": "Dumbbell"
  },
  {
    "slug": "push-press",
    "name": "Push Press",
    "muscle": "Shoulders",
    "equipment": "Barbell"
  },
  {
    "slug": "machine-lateral-raise",
    "name": "Machine Lateral Raise",
    "muscle": "Shoulders",
    "equipment": "Machine"
  },
  {
    "slug": "cable-front-raise",
    "name": "Cable Front Raise",
    "muscle": "Shoulders",
    "equipment": "Cable"
  },
  {
    "slug": "plate-front-raise",
    "name": "Plate Front Raise",
    "muscle": "Shoulders",
    "equipment": "Plate"
  },
  {
    "slug": "bent-over-rear-delt-raise",
    "name": "Bent-Over Rear Delt Raise",
    "muscle": "Rear Delts",
    "equipment": "Dumbbell"
  },
  {
    "slug": "cable-rear-delt-fly",
    "name": "Cable Rear Delt Fly",
    "muscle": "Rear Delts",
    "equipment": "Cable"
  },
  {
    "slug": "pendlay-row",
    "name": "Pendlay Row",
    "muscle": "Back",
    "equipment": "Barbell"
  },
  {
    "slug": "meadows-row",
    "name": "Meadows Row",
    "muscle": "Back",
    "equipment": "Barbell"
  },
  {
    "slug": "wide-grip-lat-pulldown",
    "name": "Wide-Grip Lat Pulldown",
    "muscle": "Lats",
    "equipment": "Cable"
  },
  {
    "slug": "neutral-grip-pull-up",
    "name": "Neutral-Grip Pull-up",
    "muscle": "Lats",
    "equipment": "Bodyweight"
  },
  {
    "slug": "assisted-chin-up",
    "name": "Assisted Chin-up",
    "muscle": "Biceps",
    "equipment": "Machine"
  },
  {
    "slug": "weighted-chin-up",
    "name": "Weighted Chin-up",
    "muscle": "Biceps",
    "equipment": "Bodyweight"
  },
  {
    "slug": "rack-pull",
    "name": "Rack Pull",
    "muscle": "Back",
    "equipment": "Barbell"
  },
  {
    "slug": "back-extension",
    "name": "Back Extension",
    "muscle": "Lower Back",
    "equipment": "Bodyweight"
  },
  {
    "slug": "smith-machine-squat",
    "name": "Smith Machine Squat",
    "muscle": "Quads",
    "equipment": "Machine"
  },
  {
    "slug": "belt-squat",
    "name": "Belt Squat",
    "muscle": "Quads",
    "equipment": "Machine"
  },
  {
    "slug": "trap-bar-deadlift",
    "name": "Trap Bar Deadlift",
    "muscle": "Posterior Chain",
    "equipment": "Barbell"
  },
  {
    "slug": "nordic-hamstring-curl",
    "name": "Nordic Hamstring Curl",
    "muscle": "Hamstrings",
    "equipment": "Bodyweight"
  },
  {
    "slug": "single-leg-romanian-deadlift",
    "name": "Single-Leg Romanian Deadlift",
    "muscle": "Hamstrings",
    "equipment": "Dumbbell"
  },
  {
    "slug": "reverse-lunge",
    "name": "Reverse Lunge",
    "muscle": "Quads",
    "equipment": "Dumbbell"
  },
  {
    "slug": "cable-kickback",
    "name": "Cable Kickback",
    "muscle": "Glutes",
    "equipment": "Cable"
  },
  {
    "slug": "single-leg-glute-bridge",
    "name": "Single-Leg Glute Bridge",
    "muscle": "Glutes",
    "equipment": "Bodyweight"
  },
  {
    "slug": "barbell-glute-bridge",
    "name": "Barbell Glute Bridge",
    "muscle": "Glutes",
    "equipment": "Barbell"
  },
  {
    "slug": "dumbbell-glute-bridge",
    "name": "Dumbbell Glute Bridge",
    "muscle": "Glutes",
    "equipment": "Dumbbell"
  },
  {
    "slug": "dumbbell-hip-thrust",
    "name": "Dumbbell Hip Thrust",
    "muscle": "Glutes",
    "equipment": "Dumbbell"
  },
  {
    "slug": "smith-machine-hip-thrust",
    "name": "Smith Machine Hip Thrust",
    "muscle": "Glutes",
    "equipment": "Machine"
  },
  {
    "slug": "smith-machine-romanian-deadlift",
    "name": "Smith Machine Romanian Deadlift",
    "muscle": "Hamstrings",
    "equipment": "Machine"
  },
  {
    "slug": "dumbbell-romanian-deadlift",
    "name": "Dumbbell Romanian Deadlift",
    "muscle": "Hamstrings",
    "equipment": "Dumbbell"
  },
  {
    "slug": "kettlebell-romanian-deadlift",
    "name": "Kettlebell Romanian Deadlift",
    "muscle": "Hamstrings",
    "equipment": "Kettlebell"
  },
  {
    "slug": "machine-glute-kickback",
    "name": "Machine Glute Kickback",
    "muscle": "Glutes",
    "equipment": "Machine"
  },
  {
    "slug": "cable-standing-hip-abduction",
    "name": "Cable Standing Hip Abduction",
    "muscle": "Glutes",
    "equipment": "Cable"
  },
  {
    "slug": "cable-standing-hip-adduction",
    "name": "Cable Standing Hip Adduction",
    "muscle": "Adductors",
    "equipment": "Cable"
  },
  {
    "slug": "hip-adduction-machine",
    "name": "Hip Adduction Machine",
    "muscle": "Adductors",
    "equipment": "Machine"
  },
  {
    "slug": "smith-machine-bulgarian-split-squat",
    "name": "Smith Machine Bulgarian Split Squat",
    "muscle": "Quads",
    "equipment": "Machine"
  },
  {
    "slug": "smith-machine-reverse-lunge",
    "name": "Smith Machine Reverse Lunge",
    "muscle": "Quads",
    "equipment": "Machine"
  },
  {
    "slug": "smith-machine-split-squat",
    "name": "Smith Machine Split Squat",
    "muscle": "Quads",
    "equipment": "Machine"
  },
  {
    "slug": "heel-elevated-goblet-squat",
    "name": "Heel-Elevated Goblet Squat",
    "muscle": "Quads",
    "equipment": "Dumbbell"
  },
  {
    "slug": "dumbbell-sumo-squat",
    "name": "Dumbbell Sumo Squat",
    "muscle": "Glutes",
    "equipment": "Dumbbell"
  },
  {
    "slug": "dumbbell-sumo-deadlift",
    "name": "Dumbbell Sumo Deadlift",
    "muscle": "Posterior Chain",
    "equipment": "Dumbbell"
  },
  {
    "slug": "front-foot-elevated-split-squat",
    "name": "Front-Foot Elevated Split Squat",
    "muscle": "Quads",
    "equipment": "Dumbbell"
  },
  {
    "slug": "deficit-reverse-lunge",
    "name": "Deficit Reverse Lunge",
    "muscle": "Glutes",
    "equipment": "Dumbbell"
  },
  {
    "slug": "dumbbell-lateral-lunge",
    "name": "Dumbbell Lateral Lunge",
    "muscle": "Quads",
    "equipment": "Dumbbell"
  },
  {
    "slug": "dumbbell-curtsy-lunge",
    "name": "Dumbbell Curtsy Lunge",
    "muscle": "Glutes",
    "equipment": "Dumbbell"
  },
  {
    "slug": "landmine-squat",
    "name": "Landmine Squat",
    "muscle": "Quads",
    "equipment": "Barbell"
  },
  {
    "slug": "landmine-romanian-deadlift",
    "name": "Landmine Romanian Deadlift",
    "muscle": "Hamstrings",
    "equipment": "Barbell"
  },
  {
    "slug": "glute-focused-back-extension",
    "name": "Glute-Focused Back Extension",
    "muscle": "Glutes",
    "equipment": "Bodyweight"
  },
  {
    "slug": "reverse-hyperextension",
    "name": "Reverse Hyperextension",
    "muscle": "Glutes",
    "equipment": "Machine"
  },
  {
    "slug": "donkey-calf-raise",
    "name": "Donkey Calf Raise",
    "muscle": "Calves",
    "equipment": "Machine"
  },
  {
    "slug": "leg-press-calf-raise",
    "name": "Leg Press Calf Raise",
    "muscle": "Calves",
    "equipment": "Machine"
  },
  {
    "slug": "jump-squat",
    "name": "Jump Squat",
    "muscle": "Quads",
    "equipment": "Bodyweight"
  },
  {
    "slug": "incline-dumbbell-curl",
    "name": "Incline Dumbbell Curl",
    "muscle": "Biceps",
    "equipment": "Dumbbell"
  },
  {
    "slug": "concentration-curl",
    "name": "Concentration Curl",
    "muscle": "Biceps",
    "equipment": "Dumbbell"
  },
  {
    "slug": "ez-bar-curl",
    "name": "EZ-Bar Curl",
    "muscle": "Biceps",
    "equipment": "Barbell"
  },
  {
    "slug": "spider-curl",
    "name": "Spider Curl",
    "muscle": "Biceps",
    "equipment": "Dumbbell"
  },
  {
    "slug": "rope-hammer-curl",
    "name": "Rope Hammer Curl",
    "muscle": "Biceps",
    "equipment": "Cable"
  },
  {
    "slug": "drag-curl",
    "name": "Drag Curl",
    "muscle": "Biceps",
    "equipment": "Barbell"
  },
  {
    "slug": "rope-tricep-pushdown",
    "name": "Rope Tricep Pushdown",
    "muscle": "Triceps",
    "equipment": "Cable"
  },
  {
    "slug": "dumbbell-skull-crusher",
    "name": "Two Dumbbell Skullcrusher",
    "muscle": "Triceps",
    "equipment": "Dumbbell"
  },
  {
    "slug": "single-dumbbell-skullcrusher",
    "name": "Single Dumbbell Skullcrusher",
    "muscle": "Triceps",
    "equipment": "Dumbbell"
  },
  {
    "slug": "dumbbell-overhead-tricep-extension",
    "name": "Dumbbell Overhead Tricep Extension",
    "muscle": "Triceps",
    "equipment": "Dumbbell"
  },
  {
    "slug": "single-arm-dumbbell-tricep-extension",
    "name": "Single Arm Dumbbell Tricep Extension",
    "muscle": "Triceps",
    "equipment": "Dumbbell"
  },
  {
    "slug": "bench-dip",
    "name": "Bench Dip",
    "muscle": "Triceps",
    "equipment": "Bodyweight"
  },
  {
    "slug": "tricep-kickback",
    "name": "Tricep Kickback",
    "muscle": "Triceps",
    "equipment": "Dumbbell"
  },
  {
    "slug": "wrist-extension",
    "name": "Wrist Extension",
    "muscle": "Forearms",
    "equipment": "Dumbbell"
  },
  {
    "slug": "crunch",
    "name": "Crunch",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "reverse-crunch",
    "name": "Reverse Crunch",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "russian-twist",
    "name": "Russian Twist",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "bicycle-crunch",
    "name": "Bicycle Crunch",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "mountain-climber",
    "name": "Mountain Climber",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "cable-woodchop",
    "name": "Cable Woodchop",
    "muscle": "Core",
    "equipment": "Cable"
  },
  {
    "slug": "half-kneeling-pallof-press",
    "name": "Half-Kneeling Pallof Press",
    "muscle": "Core",
    "equipment": "Cable"
  },
  {
    "slug": "cable-pallof-hold",
    "name": "Cable Pallof Hold",
    "muscle": "Core",
    "equipment": "Cable"
  },
  {
    "slug": "captains-chair-knee-raise",
    "name": "Captain's Chair Knee Raise",
    "muscle": "Core",
    "equipment": "Machine"
  },
  {
    "slug": "decline-sit-up",
    "name": "Decline Sit-Up",
    "muscle": "Core",
    "equipment": "Bench"
  },
  {
    "slug": "weighted-crunch",
    "name": "Weighted Crunch",
    "muscle": "Core",
    "equipment": "Plate"
  },
  {
    "slug": "weighted-russian-twist",
    "name": "Weighted Russian Twist",
    "muscle": "Core",
    "equipment": "Dumbbell"
  },
  {
    "slug": "dumbbell-side-bend",
    "name": "Dumbbell Side Bend",
    "muscle": "Core",
    "equipment": "Dumbbell"
  },
  {
    "slug": "elliptical",
    "name": "Elliptical",
    "muscle": "Legs",
    "equipment": "Cardio"
  },
  {
    "slug": "swimming",
    "name": "Swimming",
    "muscle": "Back",
    "equipment": "Cardio"
  },
  {
    "slug": "assault-bike",
    "name": "Assault Bike",
    "muscle": "Legs",
    "equipment": "Cardio"
  },
  {
    "slug": "skierg",
    "name": "SkiErg",
    "muscle": "Back",
    "equipment": "Cardio"
  },
  {
    "slug": "hiking",
    "name": "Hiking",
    "muscle": "Legs",
    "equipment": "Cardio"
  },
  {
    "slug": "treadmill-incline-walk",
    "name": "Treadmill Incline Walk",
    "muscle": "Legs",
    "equipment": "Cardio"
  },
  {
    "slug": "battle-ropes",
    "name": "Battle Ropes",
    "muscle": "Shoulders",
    "equipment": "Cardio"
  },
  {
    "slug": "knee-push-up",
    "name": "Knee Push-up",
    "muscle": "Chest",
    "equipment": "Bodyweight"
  },
  {
    "slug": "wide-push-up",
    "name": "Wide Push-up",
    "muscle": "Chest",
    "equipment": "Bodyweight"
  },
  {
    "slug": "diamond-push-up",
    "name": "Diamond Push-up",
    "muscle": "Triceps",
    "equipment": "Bodyweight"
  },
  {
    "slug": "feet-elevated-pike-push-up",
    "name": "Feet-Elevated Pike Push-up",
    "muscle": "Shoulders",
    "equipment": "Bodyweight"
  },
  {
    "slug": "archer-push-up",
    "name": "Archer Push-up",
    "muscle": "Chest",
    "equipment": "Bodyweight"
  },
  {
    "slug": "typewriter-push-up",
    "name": "Typewriter Push-up",
    "muscle": "Chest",
    "equipment": "Bodyweight"
  },
  {
    "slug": "explosive-push-up",
    "name": "Explosive Push-up",
    "muscle": "Chest",
    "equipment": "Bodyweight"
  },
  {
    "slug": "hindu-push-up",
    "name": "Hindu Push-up",
    "muscle": "Chest",
    "equipment": "Bodyweight"
  },
  {
    "slug": "scapular-push-up",
    "name": "Scapular Push-up",
    "muscle": "Upper Back",
    "equipment": "Bodyweight"
  },
  {
    "slug": "push-up-shoulder-tap",
    "name": "Push-up Shoulder Tap",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "wall-push-up",
    "name": "Wall Push-up",
    "muscle": "Chest",
    "equipment": "Wall"
  },
  {
    "slug": "wall-walk",
    "name": "Wall Walk",
    "muscle": "Shoulders",
    "equipment": "Wall"
  },
  {
    "slug": "wall-handstand-push-up",
    "name": "Wall Handstand Push-up",
    "muscle": "Shoulders",
    "equipment": "Wall"
  },
  {
    "slug": "handstand-push-up",
    "name": "Handstand Push-up",
    "muscle": "Shoulders",
    "equipment": "Bodyweight"
  },
  {
    "slug": "chair-dip",
    "name": "Chair Dip",
    "muscle": "Triceps",
    "equipment": "Chair"
  },
  {
    "slug": "doorway-row",
    "name": "Doorway Row",
    "muscle": "Back",
    "equipment": "Doorway"
  },
  {
    "slug": "towel-row",
    "name": "Towel Row",
    "muscle": "Back",
    "equipment": "Towel"
  },
  {
    "slug": "prone-y-raise",
    "name": "Prone Y Raise",
    "muscle": "Upper Back",
    "equipment": "Bodyweight"
  },
  {
    "slug": "prone-t-raise",
    "name": "Prone T Raise",
    "muscle": "Upper Back",
    "equipment": "Bodyweight"
  },
  {
    "slug": "superman-hold",
    "name": "Superman Hold",
    "muscle": "Lower Back",
    "equipment": "Bodyweight"
  },
  {
    "slug": "reverse-snow-angel",
    "name": "Reverse Snow Angel",
    "muscle": "Upper Back",
    "equipment": "Bodyweight"
  },
  {
    "slug": "dead-hang",
    "name": "Dead Hang",
    "muscle": "Forearms",
    "equipment": "Pull-up Bar"
  },
  {
    "slug": "active-hang",
    "name": "Active Hang",
    "muscle": "Lats",
    "equipment": "Pull-up Bar"
  },
  {
    "slug": "scapular-pull-up",
    "name": "Scapular Pull-up",
    "muscle": "Lats",
    "equipment": "Pull-up Bar"
  },
  {
    "slug": "negative-pull-up",
    "name": "Negative Pull-up",
    "muscle": "Lats",
    "equipment": "Pull-up Bar"
  },
  {
    "slug": "commando-pull-up",
    "name": "Commando Pull-up",
    "muscle": "Lats",
    "equipment": "Pull-up Bar"
  },
  {
    "slug": "l-sit-pull-up",
    "name": "L-Sit Pull-up",
    "muscle": "Lats",
    "equipment": "Pull-up Bar"
  },
  {
    "slug": "towel-pull-up",
    "name": "Towel Pull-up",
    "muscle": "Lats",
    "equipment": "Towel"
  },
  {
    "slug": "pistol-squat",
    "name": "Pistol Squat",
    "muscle": "Quads",
    "equipment": "Bodyweight"
  },
  {
    "slug": "assisted-pistol-squat",
    "name": "Assisted Pistol Squat",
    "muscle": "Quads",
    "equipment": "Bodyweight"
  },
  {
    "slug": "shrimp-squat",
    "name": "Shrimp Squat",
    "muscle": "Quads",
    "equipment": "Bodyweight"
  },
  {
    "slug": "cossack-squat",
    "name": "Cossack Squat",
    "muscle": "Quads",
    "equipment": "Bodyweight"
  },
  {
    "slug": "sissy-squat",
    "name": "Sissy Squat",
    "muscle": "Quads",
    "equipment": "Bodyweight"
  },
  {
    "slug": "forward-lunge",
    "name": "Forward Lunge",
    "muscle": "Quads",
    "equipment": "Bodyweight"
  },
  {
    "slug": "lateral-lunge",
    "name": "Lateral Lunge",
    "muscle": "Quads",
    "equipment": "Bodyweight"
  },
  {
    "slug": "curtsy-lunge",
    "name": "Curtsy Lunge",
    "muscle": "Glutes",
    "equipment": "Bodyweight"
  },
  {
    "slug": "skater-squat",
    "name": "Skater Squat",
    "muscle": "Quads",
    "equipment": "Bodyweight"
  },
  {
    "slug": "single-leg-box-squat",
    "name": "Single-Leg Box Squat",
    "muscle": "Quads",
    "equipment": "Box"
  },
  {
    "slug": "step-down",
    "name": "Step-Down",
    "muscle": "Quads",
    "equipment": "Box"
  },
  {
    "slug": "single-leg-calf-raise",
    "name": "Single-Leg Calf Raise",
    "muscle": "Calves",
    "equipment": "Bodyweight"
  },
  {
    "slug": "glute-bridge-march",
    "name": "Glute Bridge March",
    "muscle": "Glutes",
    "equipment": "Bodyweight"
  },
  {
    "slug": "frog-pump",
    "name": "Frog Pump",
    "muscle": "Glutes",
    "equipment": "Bodyweight"
  },
  {
    "slug": "donkey-kick",
    "name": "Donkey Kick",
    "muscle": "Glutes",
    "equipment": "Bodyweight"
  },
  {
    "slug": "fire-hydrant",
    "name": "Fire Hydrant",
    "muscle": "Glutes",
    "equipment": "Bodyweight"
  },
  {
    "slug": "clamshell",
    "name": "Clamshell",
    "muscle": "Glutes",
    "equipment": "Bodyweight"
  },
  {
    "slug": "hip-airplane",
    "name": "Hip Airplane",
    "muscle": "Glutes",
    "equipment": "Bodyweight"
  },
  {
    "slug": "side-lying-hip-abduction",
    "name": "Side-Lying Hip Abduction",
    "muscle": "Glutes",
    "equipment": "Bodyweight"
  },
  {
    "slug": "side-lying-leg-raise",
    "name": "Side-Lying Leg Raise",
    "muscle": "Glutes",
    "equipment": "Bodyweight"
  },
  {
    "slug": "lying-hamstring-walkout",
    "name": "Lying Hamstring Walkout",
    "muscle": "Hamstrings",
    "equipment": "Bodyweight"
  },
  {
    "slug": "towel-hamstring-curl",
    "name": "Towel Hamstring Curl",
    "muscle": "Hamstrings",
    "equipment": "Towel"
  },
  {
    "slug": "stability-ball-hamstring-curl",
    "name": "Stability Ball Hamstring Curl",
    "muscle": "Hamstrings",
    "equipment": "Stability Ball"
  },
  {
    "slug": "banded-glute-bridge",
    "name": "Banded Glute Bridge",
    "muscle": "Glutes",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-hip-thrust",
    "name": "Banded Hip Thrust",
    "muscle": "Glutes",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-frog-pump",
    "name": "Banded Frog Pump",
    "muscle": "Glutes",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-clamshell",
    "name": "Banded Clamshell",
    "muscle": "Glutes",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-lateral-walk",
    "name": "Banded Lateral Walk",
    "muscle": "Glutes",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-monster-walk",
    "name": "Banded Monster Walk",
    "muscle": "Glutes",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-squat",
    "name": "Banded Squat",
    "muscle": "Quads",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-donkey-kick",
    "name": "Banded Donkey Kick",
    "muscle": "Glutes",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-fire-hydrant",
    "name": "Banded Fire Hydrant",
    "muscle": "Glutes",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-kickback",
    "name": "Banded Kickback",
    "muscle": "Glutes",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-standing-hip-abduction",
    "name": "Banded Standing Hip Abduction",
    "muscle": "Glutes",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-seated-hip-abduction",
    "name": "Banded Seated Hip Abduction",
    "muscle": "Glutes",
    "equipment": "Resistance Band"
  },
  {
    "slug": "band-pull-apart",
    "name": "Band Pull-Apart",
    "muscle": "Upper Back",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-face-pull",
    "name": "Banded Face Pull",
    "muscle": "Upper Back",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-row",
    "name": "Banded Row",
    "muscle": "Back",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-lat-pulldown",
    "name": "Banded Lat Pulldown",
    "muscle": "Lats",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-pallof-press",
    "name": "Banded Pallof Press",
    "muscle": "Core",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-woodchop",
    "name": "Banded Woodchop",
    "muscle": "Core",
    "equipment": "Resistance Band"
  },
  {
    "slug": "banded-dead-bug",
    "name": "Banded Dead Bug",
    "muscle": "Core",
    "equipment": "Resistance Band"
  },
  {
    "slug": "hollow-body-hold",
    "name": "Hollow Body Hold",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "hollow-rock",
    "name": "Hollow Rock",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "v-up",
    "name": "V-Up",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "flutter-kick",
    "name": "Flutter Kick",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "lying-leg-raise",
    "name": "Lying Leg Raise",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "toe-touch",
    "name": "Toe Touch",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "heel-tap",
    "name": "Heel Tap",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "plank-shoulder-tap",
    "name": "Plank Shoulder Tap",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "plank-jack",
    "name": "Plank Jack",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "bear-plank",
    "name": "Bear Plank",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "crab-walk",
    "name": "Crab Walk",
    "muscle": "Triceps",
    "equipment": "Bodyweight"
  },
  {
    "slug": "inchworm",
    "name": "Inchworm",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "l-sit-hold",
    "name": "L-Sit Hold",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "seated-knee-tuck",
    "name": "Seated Knee Tuck",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "side-plank-hip-dip",
    "name": "Side Plank Hip Dip",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "copenhagen-plank",
    "name": "Copenhagen Plank",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "dragon-flag",
    "name": "Dragon Flag",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "half-burpee",
    "name": "Half Burpee",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "squat-thrust",
    "name": "Squat Thrust",
    "muscle": "Core",
    "equipment": "Bodyweight"
  },
  {
    "slug": "jumping-jack",
    "name": "Jumping Jack",
    "muscle": "Legs",
    "equipment": "Bodyweight"
  },
  {
    "slug": "skater-hop",
    "name": "Skater Hop",
    "muscle": "Legs",
    "equipment": "Bodyweight"
  },
  {
    "slug": "lateral-shuffle",
    "name": "Lateral Shuffle",
    "muscle": "Legs",
    "equipment": "Bodyweight"
  },
  {
    "slug": "fast-feet",
    "name": "Fast Feet",
    "muscle": "Calves",
    "equipment": "Bodyweight"
  },
  {
    "slug": "sprawl",
    "name": "Sprawl",
    "muscle": "Legs",
    "equipment": "Bodyweight"
  },
  {
    "slug": "seal-jack",
    "name": "Seal Jack",
    "muscle": "Chest",
    "equipment": "Bodyweight"
  },
  {
    "slug": "cat-cow-stretch",
    "name": "Cat-Cow Stretch",
    "muscle": "Mobility",
    "equipment": "Bodyweight"
  },
  {
    "slug": "arm-circles",
    "name": "Arm Circles",
    "muscle": "Shoulders",
    "equipment": "Bodyweight"
  },
  {
    "slug": "worlds-greatest-stretch",
    "name": "World's Greatest Stretch",
    "muscle": "Mobility",
    "equipment": "Bodyweight"
  },
  {
    "slug": "leg-swings-stretch",
    "name": "Leg Swings",
    "muscle": "Mobility",
    "equipment": "Bodyweight"
  },
  {
    "slug": "torso-twist-stretch",
    "name": "Torso Twists",
    "muscle": "Mobility",
    "equipment": "Bodyweight"
  },
  {
    "slug": "doorway-chest-stretch",
    "name": "Doorway Chest Stretch",
    "muscle": "Chest",
    "equipment": "Doorway"
  },
  {
    "slug": "childs-pose",
    "name": "Child's Pose",
    "muscle": "Back",
    "equipment": "Bodyweight"
  },
  {
    "slug": "kneeling-hip-flexor-stretch",
    "name": "Kneeling Hip Flexor Stretch",
    "muscle": "Hips",
    "equipment": "Bodyweight"
  },
  {
    "slug": "hamstring-stretch",
    "name": "Hamstring Stretch",
    "muscle": "Hamstrings",
    "equipment": "Bodyweight"
  },
  {
    "slug": "standing-quad-stretch",
    "name": "Standing Quad Stretch",
    "muscle": "Quads",
    "equipment": "Bodyweight"
  },
  {
    "slug": "seated-forward-fold-stretch",
    "name": "Seated Forward Fold",
    "muscle": "Hamstrings",
    "equipment": "Bodyweight"
  },
  {
    "slug": "cross-body-shoulder-stretch",
    "name": "Cross-Body Shoulder Stretch",
    "muscle": "Shoulders",
    "equipment": "Bodyweight"
  },
  {
    "slug": "wall-calf-stretch",
    "name": "Wall Calf Stretch",
    "muscle": "Calves",
    "equipment": "Bodyweight"
  },
  {
    "slug": "butterfly-stretch",
    "name": "Butterfly Stretch",
    "muscle": "Hips",
    "equipment": "Bodyweight"
  }
];
}

const EXERCISE_IMAGES = {
  "push-up": {
    "slug": "push-up",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Chest",
    "secondaryMuscles": [
      "Triceps",
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "incline-push-up": {
    "slug": "incline-push-up",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Chest",
    "secondaryMuscles": [
      "Triceps",
      "Shoulders",
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "incline-dumbbell-press": {
    "slug": "incline-dumbbell-press",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Chest",
    "secondaryMuscles": [
      "Shoulders",
      "Triceps"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "decline-push-up": {
    "slug": "decline-push-up",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Chest",
    "secondaryMuscles": [
      "Shoulders",
      "Triceps",
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "dumbbell-fly": {
    "slug": "dumbbell-fly",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Chest",
    "secondaryMuscles": [
      "Shoulders"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "cable-fly": {
    "slug": "cable-fly",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Chest",
    "secondaryMuscles": [
      "Shoulders"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "pull-up": {
    "slug": "pull-up",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Lats",
    "secondaryMuscles": [
      "Biceps",
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "lat-pulldown": {
    "slug": "lat-pulldown",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Lats",
    "secondaryMuscles": [
      "Biceps"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "chin-up": {
    "slug": "chin-up",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Biceps",
    "secondaryMuscles": [
      "Lats"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "inverted-row": {
    "slug": "inverted-row",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Back",
    "secondaryMuscles": [
      "Biceps",
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "barbell-row": {
    "slug": "barbell-row",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Back",
    "secondaryMuscles": [
      "Biceps",
      "Rear Delts"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "straight-arm-pulldown": {
    "slug": "straight-arm-pulldown",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Lats",
    "secondaryMuscles": [
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "single-arm-cable-row": {
    "slug": "single-arm-cable-row",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Back",
    "secondaryMuscles": [
      "Biceps",
      "Rear Delts"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "chest-supported-row": {
    "slug": "chest-supported-row",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Back",
    "secondaryMuscles": [
      "Biceps",
      "Rear Delts"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "bodyweight-squat": {
    "slug": "bodyweight-squat",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Quads",
    "secondaryMuscles": [
      "Glutes",
      "Hamstrings",
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "goblet-squat": {
    "slug": "goblet-squat",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Quads",
    "secondaryMuscles": [
      "Glutes",
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "front-squat": {
    "slug": "front-squat",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Quads",
    "secondaryMuscles": [
      "Core",
      "Glutes"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "romanian-deadlift": {
    "slug": "romanian-deadlift",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Hamstrings",
    "secondaryMuscles": [
      "Glutes",
      "Lower Back"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "sumo-deadlift": {
    "slug": "sumo-deadlift",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Posterior Chain",
    "secondaryMuscles": [
      "Glutes",
      "Quads"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "good-morning": {
    "slug": "good-morning",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Hamstrings",
    "secondaryMuscles": [
      "Glutes",
      "Lower Back"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "hip-thrust": {
    "slug": "hip-thrust",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Glutes",
    "secondaryMuscles": [
      "Hamstrings"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "leg-press": {
    "slug": "leg-press",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Quads",
    "secondaryMuscles": [
      "Glutes",
      "Hamstrings"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "hip-abduction-machine": {
    "slug": "hip-abduction-machine",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Glutes",
    "secondaryMuscles": [
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "glute-bridge": {
    "slug": "glute-bridge",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Glutes",
    "secondaryMuscles": [
      "Hamstrings"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "split-squat": {
    "slug": "split-squat",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Quads",
    "secondaryMuscles": [
      "Glutes",
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "bulgarian-split-squat": {
    "slug": "bulgarian-split-squat",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Quads",
    "secondaryMuscles": [
      "Glutes",
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "step-up": {
    "slug": "step-up",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Quads",
    "secondaryMuscles": [
      "Glutes"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "wall-sit": {
    "slug": "wall-sit",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Quads",
    "secondaryMuscles": [
      "Glutes",
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "calf-raise": {
    "slug": "calf-raise",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Calves",
    "secondaryMuscles": [],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "arnold-press": {
    "slug": "arnold-press",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Shoulders",
    "secondaryMuscles": [
      "Triceps"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "pike-push-up": {
    "slug": "pike-push-up",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Shoulders",
    "secondaryMuscles": [
      "Triceps",
      "Chest",
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "lateral-raise": {
    "slug": "lateral-raise",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Shoulders",
    "secondaryMuscles": [
      "Upper Back"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "rear-delt-fly": {
    "slug": "rear-delt-fly",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Rear Delts",
    "secondaryMuscles": [
      "Upper Back"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "face-pull": {
    "slug": "face-pull",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Upper Back",
    "secondaryMuscles": [
      "Rear Delts",
      "Shoulders"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "dumbbell-shrug": {
    "slug": "dumbbell-shrug",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Upper Back",
    "secondaryMuscles": [
      "Forearms"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "bicep-curl": {
    "slug": "bicep-curl",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Biceps",
    "secondaryMuscles": [
      "Forearms"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "hammer-curl": {
    "slug": "hammer-curl",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Biceps",
    "secondaryMuscles": [
      "Forearms"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "tricep-pushdown": {
    "slug": "tricep-pushdown",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Triceps",
    "secondaryMuscles": [
      "Shoulders"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "overhead-tricep-extension": {
    "slug": "overhead-tricep-extension",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Triceps",
    "secondaryMuscles": [
      "Shoulders"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "plank": {
    "slug": "plank",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Core",
    "secondaryMuscles": [
      "Shoulders"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "side-plank": {
    "slug": "side-plank",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Core",
    "secondaryMuscles": [
      "Shoulders"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "dead-bug": {
    "slug": "dead-bug",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Core",
    "secondaryMuscles": [
      "Legs"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "bird-dog": {
    "slug": "bird-dog",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Core",
    "secondaryMuscles": [
      "Glutes",
      "Shoulders"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "pallof-press": {
    "slug": "pallof-press",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Core",
    "secondaryMuscles": [
      "Shoulders"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "hanging-knee-raise": {
    "slug": "hanging-knee-raise",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Core",
    "secondaryMuscles": [
      "Grip"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "high-knees": {
    "slug": "high-knees",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Legs",
    "secondaryMuscles": [
      "Core",
      "Cardio"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "jump-rope": {
    "slug": "jump-rope",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Calves",
    "secondaryMuscles": [
      "Cardio",
      "Shoulders"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "kettlebell-swing": {
    "slug": "kettlebell-swing",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Glutes",
    "secondaryMuscles": [
      "Hamstrings",
      "Core",
      "Cardio"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "bear-crawl": {
    "slug": "bear-crawl",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Core",
    "secondaryMuscles": [
      "Shoulders",
      "Quads",
      "Cardio"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "burpee": {
    "slug": "burpee",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Legs",
    "secondaryMuscles": [
      "Chest",
      "Shoulders",
      "Core",
      "Cardio"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "farmer-carry": {
    "slug": "farmer-carry",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Forearms",
    "secondaryMuscles": [
      "Upper Back",
      "Core"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "superman": {
    "slug": "superman",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Lower Back",
    "secondaryMuscles": [
      "Glutes",
      "Upper Back",
      "Hamstrings"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "lying-leg-curl": {
    "slug": "lying-leg-curl",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Hamstrings",
    "secondaryMuscles": [
      "Calves"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "cable-pull-through": {
    "slug": "cable-pull-through",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Glutes",
    "secondaryMuscles": [
      "Hamstrings",
      "Lower Back"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "machine-shoulder-press": {
    "slug": "machine-shoulder-press",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Shoulders",
    "secondaryMuscles": [
      "Triceps"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "reverse-pec-deck": {
    "slug": "reverse-pec-deck",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Rear Delts",
    "secondaryMuscles": [
      "Upper Back"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "bench-press-barbell": {
    "slug": "bench-press",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Chest",
    "secondaryMuscles": [
      "Triceps",
      "Shoulders"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "overhead-press-barbell": {
    "slug": "overhead-press",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Shoulders",
    "secondaryMuscles": [
      "Triceps"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "dumbbell-row": {
    "slug": "one-arm-dumbbell-row",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Back",
    "secondaryMuscles": [
      "Biceps"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "cable-row": {
    "slug": "seated-row",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Back",
    "secondaryMuscles": [
      "Biceps",
      "Rear Delts"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  },
  "tricep-dip-bench": {
    "slug": "dip",
    "frames": [
      1,
      2,
      3
    ],
    "primaryMuscle": "Triceps",
    "secondaryMuscles": [
      "Chest",
      "Shoulders"
    ],
    "isStretch": false,
    "license": "CC BY-SA 4.0",
    "creator": "Bryl Lim"
  }
};
